//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillromAutomationFramework.PageObjects.UpdatesTab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceMonitorPageExpectedValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMonitorPageExpectedValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HillromAutomationFramework.PageObjects.UpdatesTab.ServiceMonitorPageExpectedValue" +
                            "s", typeof(ServiceMonitorPageExpectedValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1D (24 HOURS).
        /// </summary>
        internal static string CallHomePeriodDropdownOptionP1D {
            get {
                return ResourceManager.GetString("CallHomePeriodDropdownOptionP1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1D.
        /// </summary>
        internal static string CallHomePeriodDropdownOptionP1DPatialText {
            get {
                return ResourceManager.GetString("CallHomePeriodDropdownOptionP1DPatialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT15M (15 MINUTES).
        /// </summary>
        internal static string CallHomePeriodDropdownOptionPT15M {
            get {
                return ResourceManager.GetString("CallHomePeriodDropdownOptionPT15M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT4H (4 HOURS).
        /// </summary>
        internal static string CallHomePeriodDropdownOptionPT4H {
            get {
                return ResourceManager.GetString("CallHomePeriodDropdownOptionPT4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT8H (8 HOURS).
        /// </summary>
        internal static string CallHomePeriodDropdownOptionPT8H {
            get {
                return ResourceManager.GetString("CallHomePeriodDropdownOptionPT8H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call home Period.
        /// </summary>
        internal static string CallHomePeriodLabel {
            get {
                return ResourceManager.GetString("CallHomePeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE.
        /// </summary>
        internal static string DeploymentModeDropdownOptionFalse {
            get {
                return ResourceManager.GetString("DeploymentModeDropdownOptionFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string DeploymentModeDropdownOptionFalsePartialText {
            get {
                return ResourceManager.GetString("DeploymentModeDropdownOptionFalsePartialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        internal static string DeploymentModeDropdownOptionTrue {
            get {
                return ResourceManager.GetString("DeploymentModeDropdownOptionTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment mode.
        /// </summary>
        internal static string DeploymentModeLabel {
            get {
                return ResourceManager.GetString("DeploymentModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 devices in 1 locations.
        /// </summary>
        internal static string Destination1DeviceCountText {
            get {
                return ResourceManager.GetString("Destination1DeviceCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINATIONS.
        /// </summary>
        internal static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 devices in 0 locations.
        /// </summary>
        internal static string DestinationNoDeviceCountText {
            get {
                return ResourceManager.GetString("DestinationNoDeviceCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /right_disabled.png.
        /// </summary>
        internal static string PaginationNextIconDisabledSrc {
            get {
                return ResourceManager.GetString("PaginationNextIconDisabledSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /left_disabled.png.
        /// </summary>
        internal static string PaginationPreviousIconDisabledSrc {
            get {
                return ResourceManager.GetString("PaginationPreviousIconDisabledSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Monitor Settings.
        /// </summary>
        internal static string ServiceMoniterLabel {
            get {
                return ResourceManager.GetString("ServiceMoniterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Monitor.
        /// </summary>
        internal static string ServiceMoniterText {
            get {
                return ResourceManager.GetString("ServiceMoniterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update process has been established.
        /// </summary>
        internal static string UpdateMessageText {
            get {
                return ResourceManager.GetString("UpdateMessageText", resourceCulture);
            }
        }
    }
}
