//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillromAutomationFramework.PageObjects.UpdatesTab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateSelectDevicesPageExpectedValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateSelectDevicesPageExpectedValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HillromAutomationFramework.PageObjects.UpdatesTab.UpdateSelectDevicesPageExpected" +
                            "Values", typeof(UpdateSelectDevicesPageExpectedValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrella.
        /// </summary>
        internal static string CentrellaDeviceName {
            get {
                return ResourceManager.GetString("CentrellaDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ConfigureLabelText {
            get {
                return ResourceManager.GetString("ConfigureLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connex Spot Monitor.
        /// </summary>
        internal static string CSMDeviceName {
            get {
                return ResourceManager.GetString("CSMDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 assets selected in 1 locations.
        /// </summary>
        internal static string Desination1DeviceCountText {
            get {
                return ResourceManager.GetString("Desination1DeviceCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINATIONS.
        /// </summary>
        internal static string DestinationLabelText {
            get {
                return ResourceManager.GetString("DestinationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla-signed.waconfig.
        /// </summary>
        internal static string FirstConfigFileName {
            get {
                return ResourceManager.GetString("FirstConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgba(84, 104, 229, 1).
        /// </summary>
        internal static string HighlightedHeadingColor {
            get {
                return ResourceManager.GetString("HighlightedHeadingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to push.
        /// </summary>
        internal static string ItemToPushLabelText {
            get {
                return ResourceManager.GetString("ItemToPushLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgba(68, 68, 68, 1).
        /// </summary>
        internal static string NonHighlightedHeadingColor {
            get {
                return ResourceManager.GetString("NonHighlightedHeadingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RV700.
        /// </summary>
        internal static string RV700DeviceName {
            get {
                return ResourceManager.GetString("RV700DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update process has been established.
        /// </summary>
        internal static string UpdateProcessMessageText {
            get {
                return ResourceManager.GetString("UpdateProcessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string UpgradeLabelText {
            get {
                return ResourceManager.GetString("UpgradeLabelText", resourceCulture);
            }
        }
    }
}
