//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillromAutomationFramework.PageObjects.AdvancedTab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdvancePageExpectedValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdvancePageExpectedValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HillromAutomationFramework.PageObjects.AdvancedTab.AdvancePageExpectedValues", typeof(AdvancePageExpectedValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD USER.
        /// </summary>
        internal static string AddUserListPageText {
            get {
                return ResourceManager.GetString("AddUserListPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT USER.
        /// </summary>
        internal static string EditUserPageLabelText {
            get {
                return ResourceManager.GetString("EditUserPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name.
        /// </summary>
        internal static string FullNameErrorMessage {
            get {
                return ResourceManager.GetString("FullNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltts_testing@hillrom.com.
        /// </summary>
        internal static string LoggedUser {
            get {
                return ResourceManager.GetString("LoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        internal static string PhoneNumberErrorMessage {
            get {
                return ResourceManager.GetString("PhoneNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltts_testing@hillrom.com.
        /// </summary>
        internal static string SuperAdminUsername {
            get {
                return ResourceManager.GetString("SuperAdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex Hasi.
        /// </summary>
        internal static string UpdatedFullName {
            get {
                return ResourceManager.GetString("UpdatedFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information:.
        /// </summary>
        internal static string UserInformationLabel {
            get {
                return ResourceManager.GetString("UserInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER LIST.
        /// </summary>
        internal static string UserListPageLabelText {
            get {
                return ResourceManager.GetString("UserListPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagementLabelTextOnEditUserPage {
            get {
                return ResourceManager.GetString("UserManagementLabelTextOnEditUserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string UserRoleAdministratorOnUserListPage {
            get {
                return ResourceManager.GetString("UserRoleAdministratorOnUserListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string UserRoleRegularOnUserListPage {
            get {
                return ResourceManager.GetString("UserRoleRegularOnUserListPage", resourceCulture);
            }
        }
    }
}
