//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillromAutomationFramework.PageObjects.ReportsTab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FirmwareStatusReportPageExpectedValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FirmwareStatusReportPageExpectedValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HillromAutomationFramework.PageObjects.ReportsTab.FirmwareStatusReportPageExpecte" +
                            "dValues", typeof(FirmwareStatusReportPageExpectedValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when downloading the firmware..
        /// </summary>
        internal static string CentrellaDownloadFailureDefination {
            get {
                return ResourceManager.GetString("CentrellaDownloadFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware is downloading on the bed..
        /// </summary>
        internal static string CentrellaDownloadingDefination {
            get {
                return ResourceManager.GetString("CentrellaDownloadingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware_Status_Report.csv.
        /// </summary>
        internal static string CentrellaFirmwareStatusReportName {
            get {
                return ResourceManager.GetString("CentrellaFirmwareStatusReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.33.006.
        /// </summary>
        internal static string CentrellaFirmwareVersionSearchText {
            get {
                return ResourceManager.GetString("CentrellaFirmwareVersionSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrella Firmware Report Statuses:.
        /// </summary>
        internal static string CentrellaInformationPopUpHeaderText {
            get {
                return ResourceManager.GetString("CentrellaInformationPopUpHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.35.612.
        /// </summary>
        internal static string CentrellaLastDeployedSearchText {
            get {
                return ResourceManager.GetString("CentrellaLastDeployedSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batesville.
        /// </summary>
        internal static string CentrellaLocationSearchText {
            get {
                return ResourceManager.GetString("CentrellaLocationSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PY673002.
        /// </summary>
        internal static string CentrellaSerialNumberSearchText {
            get {
                return ResourceManager.GetString("CentrellaSerialNumberSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boards have received the firmware..
        /// </summary>
        internal static string CentrellaStagingCompleteDefination {
            get {
                return ResourceManager.GetString("CentrellaStagingCompleteDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware is distributing to the boards..
        /// </summary>
        internal static string CentrellaStagingDefination {
            get {
                return ResourceManager.GetString("CentrellaStagingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when distributing the firmware to the boards..
        /// </summary>
        internal static string CentrellaStagingFailureDefination {
            get {
                return ResourceManager.GetString("CentrellaStagingFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded firmware and boards are inconsistent. Bed features may not work as expected..
        /// </summary>
        internal static string CentrellaStagingInconsistentDefination {
            get {
                return ResourceManager.GetString("CentrellaStagingInconsistentDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been sent to update the firmware on the bed..
        /// </summary>
        internal static string CentrellaStartedDefination {
            get {
                return ResourceManager.GetString("CentrellaStartedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string CentrellaStatusSearchText {
            get {
                return ResourceManager.GetString("CentrellaStatusSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred during the new firmware application to boards..
        /// </summary>
        internal static string CentrellaToggeleFailureDefination {
            get {
                return ResourceManager.GetString("CentrellaToggeleFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update is complete. A bed restart is required to apply the new firmware..
        /// </summary>
        internal static string CentrellaTogglingCompleteDefination {
            get {
                return ResourceManager.GetString("CentrellaTogglingCompleteDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bed is updating to the new firmware..
        /// </summary>
        internal static string CentrellaTogglingDefination {
            get {
                return ResourceManager.GetString("CentrellaTogglingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bed successfully updated to the new firmware..
        /// </summary>
        internal static string CentrellaUpgradeSuccessDefination {
            get {
                return ResourceManager.GetString("CentrellaUpgradeSuccessDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update successful. Device is currently running the new firmware..
        /// </summary>
        internal static string CSMAppliedDefination {
            get {
                return ResourceManager.GetString("CSMAppliedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update has been received by Service Monitor and is waiting for device to call home..
        /// </summary>
        internal static string CSMAvailableDefination {
            get {
                return ResourceManager.GetString("CSMAvailableDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation of the Firmware update has been received and is awaiting device confirmation..
        /// </summary>
        internal static string CSMCancelingDefination {
            get {
                return ResourceManager.GetString("CSMCancelingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation of the Firmware update has been requested..
        /// </summary>
        internal static string CSMCancelRequestedDefination {
            get {
                return ResourceManager.GetString("CSMCancelRequestedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New firmware is available on the device..
        /// </summary>
        internal static string CSMDownloadedDefination {
            get {
                return ResourceManager.GetString("CSMDownloadedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download of Firmware update to the device has failed. Download will attempt again at next call home..
        /// </summary>
        internal static string CSMDownloadFailedDefination {
            get {
                return ResourceManager.GetString("CSMDownloadFailedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update is actively downloading to the device..
        /// </summary>
        internal static string CSMDownloadingDefination {
            get {
                return ResourceManager.GetString("CSMDownloadingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update aborted. Check device log for details..
        /// </summary>
        internal static string CSMFailedDefination {
            get {
                return ResourceManager.GetString("CSMFailedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware_Status_Report.csv.
        /// </summary>
        internal static string CSMFirmwareStatusReportName {
            get {
                return ResourceManager.GetString("CSMFirmwareStatusReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.00.00-A0001.
        /// </summary>
        internal static string CSMFirmwareVersionSearchText {
            get {
                return ResourceManager.GetString("CSMFirmwareVersionSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSM Firmware Report Statuses:.
        /// </summary>
        internal static string CSMInformationPopUPHeaderText {
            get {
                return ResourceManager.GetString("CSMInformationPopUPHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.52.00-A0002.
        /// </summary>
        internal static string CSMLastDeployedSearchText {
            get {
                return ResourceManager.GetString("CSMLastDeployedSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station2.
        /// </summary>
        internal static string CSMLocationSearchText {
            get {
                return ResourceManager.GetString("CSMLocationSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update is downloaded to the device, and awaiting scheduled time to apply the update..
        /// </summary>
        internal static string CSMScheduledDefination {
            get {
                return ResourceManager.GetString("CSMScheduledDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100010000000.
        /// </summary>
        internal static string CSMSerialNumberSearchText {
            get {
                return ResourceManager.GetString("CSMSerialNumberSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update has been initiated..
        /// </summary>
        internal static string CSMStartedDefinition {
            get {
                return ResourceManager.GetString("CSMStartedDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string CSMStatusSearchText {
            get {
                return ResourceManager.GetString("CSMStatusSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is currently installing the new firmware..
        /// </summary>
        internal static string CSMUpdatingDefination {
            get {
                return ResourceManager.GetString("CSMUpdatingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMWARE UPGRADE STATUS (CENTRELLA).
        /// </summary>
        internal static string FirmwareUpgradeStatusCentrellaLabel {
            get {
                return ResourceManager.GetString("FirmwareUpgradeStatusCentrellaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMWARE UPGRADE STATUS (CSM).
        /// </summary>
        internal static string FirmwareUpgradeStatusCSMLabel {
            get {
                return ResourceManager.GetString("FirmwareUpgradeStatusCSMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMWARE UPGRADE STATUS (PROGRESSA).
        /// </summary>
        internal static string FirmwareUpgradeStatusProgressaLabel {
            get {
                return ResourceManager.GetString("FirmwareUpgradeStatusProgressaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMWARE UPGRADE STATUS (RV700).
        /// </summary>
        internal static string FirmwareUpgradeStatusRV700Label {
            get {
                return ResourceManager.GetString("FirmwareUpgradeStatusRV700Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when downloading the firmware. Attempt the firmware update process again..
        /// </summary>
        internal static string ProgressaDownloadFailureDefination {
            get {
                return ResourceManager.GetString("ProgressaDownloadFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware is downloading on the bed..
        /// </summary>
        internal static string ProgressaDownloadingDefination {
            get {
                return ResourceManager.GetString("ProgressaDownloadingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware_Status_Report.csv.
        /// </summary>
        internal static string ProgressaFirmwareStatusReportName {
            get {
                return ResourceManager.GetString("ProgressaFirmwareStatusReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22013101.
        /// </summary>
        internal static string ProgressaFirmwareVersionSearchText {
            get {
                return ResourceManager.GetString("ProgressaFirmwareVersionSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded firmware is inconsistent OR does not support Remote Service. Check the firmware release notes and attempt the firmware update process again..
        /// </summary>
        internal static string ProgressaInconsistentSoftwareErrorDefination {
            get {
                return ResourceManager.GetString("ProgressaInconsistentSoftwareErrorDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressa Firmware Report Statuses:.
        /// </summary>
        internal static string ProgressaInformationPopUpHeaderText {
            get {
                return ResourceManager.GetString("ProgressaInformationPopUpHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bed is preparing the firmware update process after a user input is received on the bed side..
        /// </summary>
        internal static string ProgressaInitializingDefination {
            get {
                return ResourceManager.GetString("ProgressaInitializingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when initializing the firmware update, after a user input is received on the bed side. Check the firmware release notes and attempt the firmware update process again..
        /// </summary>
        internal static string ProgressaInitializingFailureDefination {
            get {
                return ResourceManager.GetString("ProgressaInitializingFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21121901.
        /// </summary>
        internal static string ProgressaLastDeployedSearchText {
            get {
                return ResourceManager.GetString("ProgressaLastDeployedSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update at the bedside was initiated. The remote firmware update is cancelled..
        /// </summary>
        internal static string ProgressaLocalUpgradePerformedDefination {
            get {
                return ResourceManager.GetString("ProgressaLocalUpgradePerformedDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batesville.
        /// </summary>
        internal static string ProgressaLocationSearchText {
            get {
                return ResourceManager.GetString("ProgressaLocationSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware is mounted on the virtual USB drive to initiate update..
        /// </summary>
        internal static string ProgressaMountingCompleteDefination {
            get {
                return ResourceManager.GetString("ProgressaMountingCompleteDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware is mounting on the virtual USB drive to initiate update..
        /// </summary>
        internal static string ProgressaMountingDefination {
            get {
                return ResourceManager.GetString("ProgressaMountingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when mounting the firmware to the board. Check the firmware release notes and attempt the firmware update process again..
        /// </summary>
        internal static string ProgressaMountingFailureDefination {
            get {
                return ResourceManager.GetString("ProgressaMountingFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PY685004.
        /// </summary>
        internal static string ProgressaSerialNumberSearchText {
            get {
                return ResourceManager.GetString("ProgressaSerialNumberSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware is distributing to the boards..
        /// </summary>
        internal static string ProgressaStagingDefination {
            get {
                return ResourceManager.GetString("ProgressaStagingDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when distributing the firmware to the board. See DTC code of the failure for more troubleshooting instructions..
        /// </summary>
        internal static string ProgressaStagingFailureDefination {
            get {
                return ResourceManager.GetString("ProgressaStagingFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string ProgressaStatusSearchText {
            get {
                return ResourceManager.GetString("ProgressaStatusSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bed is updating the new firmware to WAM board..
        /// </summary>
        internal static string ProgressaUpdatingWAMDefination {
            get {
                return ResourceManager.GetString("ProgressaUpdatingWAMDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bed successfully updated to the new firmware..
        /// </summary>
        internal static string ProgressaUpgradeSuccessDefination {
            get {
                return ResourceManager.GetString("ProgressaUpgradeSuccessDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred when updating the firmware to the WAM board. Attempt the firmware update process again..
        /// </summary>
        internal static string ProgressaWamUpdateFailureDefination {
            get {
                return ResourceManager.GetString("ProgressaWamUpdateFailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update has been deployed and is waiting for device to call home..
        /// </summary>
        internal static string RV700AvailableDefination {
            get {
                return ResourceManager.GetString("RV700AvailableDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device firmware upgrade is complete..
        /// </summary>
        internal static string RV700CompleteDefination {
            get {
                return ResourceManager.GetString("RV700CompleteDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device firmware upgrade has failed..
        /// </summary>
        internal static string RV700FailureDefination {
            get {
                return ResourceManager.GetString("RV700FailureDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware_Status_Report.csv.
        /// </summary>
        internal static string RV700FirmwareStatusReportName {
            get {
                return ResourceManager.GetString("RV700FirmwareStatusReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RV700 Firmware Report Statuses:.
        /// </summary>
        internal static string RV700InformationPopUPHeaderText {
            get {
                return ResourceManager.GetString("RV700InformationPopUPHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update has been initiated..
        /// </summary>
        internal static string RV700StartedDefinition {
            get {
                return ResourceManager.GetString("RV700StartedDefinition", resourceCulture);
            }
        }
    }
}
