//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillromAutomationFramework.PageObjects.LoginPageObject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginPageExpectedValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginPageExpectedValue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HillromAutomationFramework.PageObjects.LoginPageObject.LoginPageExpectedValue", typeof(LoginPageExpectedValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/content/dam/hillrom-aem/us/en/sap-documents/LIT/80028/80028398LITPDF.pdf.
        /// </summary>
        internal static string AdminstartorsGuidePDFURL {
            get {
                return ResourceManager.GetString("AdminstartorsGuidePDFURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartCare™.
        /// </summary>
        internal static string ApplicationTitleText {
            get {
                return ResourceManager.GetString("ApplicationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2021 Hillrom™..
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCP.zip.
        /// </summary>
        internal static string DCPFileName {
            get {
                return ResourceManager.GetString("DCPFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string EmailFieldHintText {
            get {
                return ResourceManager.GetString("EmailFieldHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email with a link to update your password.
        /// </summary>
        internal static string ForgotPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn the value of the SmartCare™ Remote Management, download software, and access documentation..
        /// </summary>
        internal static string GetStartedMessageText {
            get {
                return ResourceManager.GetString("GetStartedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started?.
        /// </summary>
        internal static string GetStartedTitleText {
            get {
                return ResourceManager.GetString("GetStartedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/content/dam/hillrom-aem/us/en/sap-documents/LIT/80028/80028397LITPDF.pdf.
        /// </summary>
        internal static string InstructionForUsePDFURL {
            get {
                return ResourceManager.GetString("InstructionForUsePDFURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password invalid..
        /// </summary>
        internal static string InvalidEntryErrorMessage {
            get {
                return ResourceManager.GetString("InvalidEntryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartCare™ Remote Management.
        /// </summary>
        internal static string LandingPageTitle {
            get {
                return ResourceManager.GetString("LandingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials to sign in..
        /// </summary>
        internal static string LoginInstructionsText {
            get {
                return ResourceManager.GetString("LoginInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full authentication is required to access this resource.
        /// </summary>
        internal static string NoEntryErrorMessage {
            get {
                return ResourceManager.GetString("NoEntryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerConnect.zip.
        /// </summary>
        internal static string PartnerConnectFileName {
            get {
                return ResourceManager.GetString("PartnerConnectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordFieldHintText {
            get {
                return ResourceManager.GetString("PasswordFieldHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/content/dam/hillrom-aem/us/en/sap-documents/LIT/80028/80028399LITPDF.pdf.
        /// </summary>
        internal static string RealeaseNotesPDFURL {
            get {
                return ResourceManager.GetString("RealeaseNotesPDFURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string RightsReservedMessage {
            get {
                return ResourceManager.GetString("RightsReservedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceMonitor.zip.
        /// </summary>
        internal static string ServiceMonitorFileName {
            get {
                return ResourceManager.GetString("ServiceMonitorFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Safari : iOS 14 and higher.
        /// </summary>
        internal static string SupportedBrowserAppleSafari {
            get {
                return ResourceManager.GetString("SupportedBrowserAppleSafari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome : version 86 and higher.
        /// </summary>
        internal static string SupportedBrowserChrome {
            get {
                return ResourceManager.GetString("SupportedBrowserChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Edge : version 89 and higher.
        /// </summary>
        internal static string SupportedBrowserEdge {
            get {
                return ResourceManager.GetString("SupportedBrowserEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string TermsOfUseTitle {
            get {
                return ResourceManager.GetString("TermsOfUseTitle", resourceCulture);
            }
        }
    }
}
