//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillromAutomationFramework.PageObjects.AssetsTab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainPageExpectedValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageExpectedValue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HillromAutomationFramework.PageObjects.AssetsTab.MainPageExpectedValue", typeof(MainPageExpectedValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All assets.
        /// </summary>
        internal static string AllAssetsText {
            get {
                return ResourceManager.GetString("AllAssetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string AllOrganizationsDevicesListWithRollUp {
            get {
                return ResourceManager.GetString("AllOrganizationsDevicesListWithRollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSS Service,L&amp;T Automated Test,L&amp;T Automated Test East,LT Automated Eye Test.
        /// </summary>
        internal static string AllOrgnaizationText {
            get {
                return ResourceManager.GetString("AllOrgnaizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset tag.
        /// </summary>
        internal static string AssetTagHeadingText {
            get {
                return ResourceManager.GetString("AssetTagHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset type.
        /// </summary>
        internal static string AssetTypeLabelText {
            get {
                return ResourceManager.GetString("AssetTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrella.
        /// </summary>
        internal static string CentrellaDeviceName {
            get {
                return ResourceManager.GetString("CentrellaDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file.
        /// </summary>
        internal static string ConfigFileHeadingText {
            get {
                return ResourceManager.GetString("ConfigFileHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/en/about-us/contact-us/.
        /// </summary>
        internal static string ContactUsURL {
            get {
                return ResourceManager.GetString("ContactUsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connex Spot Monitor (CSM).
        /// </summary>
        internal static string CSMDeviceName {
            get {
                return ResourceManager.GetString("CSMDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connex Vital Signs Monitor (CVSM).
        /// </summary>
        internal static string CVSMDeviceName {
            get {
                return ResourceManager.GetString("CVSMDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        internal static string FirmwareHeadingText {
            get {
                return ResourceManager.GetString("FirmwareHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/en/services/.
        /// </summary>
        internal static string GlobalServiceCenterURL {
            get {
                return ResourceManager.GetString("GlobalServiceCenterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICV.
        /// </summary>
        internal static string InvalidPartialString {
            get {
                return ResourceManager.GetString("InvalidPartialString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last connected.
        /// </summary>
        internal static string LastConnectedHeadingText {
            get {
                return ResourceManager.GetString("LastConnectedHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 194.
        /// </summary>
        internal static string LNTAutomatedTestOrganizationDeviceCount {
            get {
                return ResourceManager.GetString("LNTAutomatedTestOrganizationDeviceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&amp;T Automated Test
        ///Test1.
        /// </summary>
        internal static string LNTAutomatedTestOrganizationFacilityTest1Text {
            get {
                return ResourceManager.GetString("LNTAutomatedTestOrganizationFacilityTest1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&amp;T Automated Test
        ///Test1
        ///Station1.
        /// </summary>
        internal static string LNTAutomatedTestOrganizationFacilityTest1UnitStation1Text {
            get {
                return ResourceManager.GetString("LNTAutomatedTestOrganizationFacilityTest1UnitStation1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationHeadingText {
            get {
                return ResourceManager.GetString("LocationHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LT Automated Eye Test.
        /// </summary>
        internal static string LTAutomatedEyeTestOrgnaizationText {
            get {
                return ResourceManager.GetString("LTAutomatedEyeTestOrgnaizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP=B4:DE:31:0B:91:E4.
        /// </summary>
        internal static string MACAddressText {
            get {
                return ResourceManager.GetString("MACAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string MACTotalRecords {
            get {
                return ResourceManager.GetString("MACTotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string OrganizationLabelText {
            get {
                return ResourceManager.GetString("OrganizationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        internal static string PartialAssetTagText {
            get {
                return ResourceManager.GetString("PartialAssetTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.52.
        /// </summary>
        internal static string PartialFirmwareVersionText {
            get {
                return ResourceManager.GetString("PartialFirmwareVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001.
        /// </summary>
        internal static string PartialSerialNumberText {
            get {
                return ResourceManager.GetString("PartialSerialNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        internal static string PartialTypeText {
            get {
                return ResourceManager.GetString("PartialTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM due.
        /// </summary>
        internal static string PmDueHeadingText {
            get {
                return ResourceManager.GetString("PmDueHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/en/about-us/global-privacy-notice/.
        /// </summary>
        internal static string PrivacyPolicyURL {
            get {
                return ResourceManager.GetString("PrivacyPolicyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58.
        /// </summary>
        internal static string PSSServiceBastesvilleDeviceCount {
            get {
                return ResourceManager.GetString("PSSServiceBastesvilleDeviceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetinaVue 700 (RV700).
        /// </summary>
        internal static string RV700DeviceName {
            get {
                return ResourceManager.GetString("RV700DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchFieldHintText {
            get {
                return ResourceManager.GetString("SearchFieldHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string SerialNumberHeadingText {
            get {
                return ResourceManager.GetString("SerialNumberHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusHeadingText {
            get {
                return ResourceManager.GetString("StatusHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hillrom.com/en/about-us/hill-rom-terms-and-conditions/.
        /// </summary>
        internal static string TermsAndConditonsURL {
            get {
                return ResourceManager.GetString("TermsAndConditonsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeHeadingText {
            get {
                return ResourceManager.GetString("TypeHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        internal static string ValidPartialString {
            get {
                return ResourceManager.GetString("ValidPartialString", resourceCulture);
            }
        }
    }
}
